// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "example.com/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: ctx, m
func (_m *Repository) CreateBook(ctx context.Context, m *models.Book) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Book) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteBook(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]*models.Book, error) {
	ret := _m.Called(ctx)

	var r0 []*models.Book
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Book); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id, m
func (_m *Repository) GetById(ctx context.Context, id int64, m *models.Book) error {
	ret := _m.Called(ctx, id, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Book) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBook provides a mock function with given fields: ctx, id, m
func (_m *Repository) UpdateBook(ctx context.Context, id int64, m *models.Book) error {
	ret := _m.Called(ctx, id, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Book) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
